config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  devise_for :users
  root to: 'pages#home'

  resources :items do
    get 'like'
    get 'dislike'
    member do
      get 'potential_matches'
    end
  end

  resources :matches, only: [:create, :index, :update] do
    # post 'exchanged'
    resources :chat_rooms, only: [ :show, :create ]
  end
  resources :chat_rooms, only: [] do
      resources :messages, only: [ :create ]
  end


end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :messages, dependent: :destroy
  # belongs_to :match
  # validates :match_id, uniqueness: :true
  # first i need to add match_id to the Matches table
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def show
    # raise
    @match_chat_room_messages = ChatRoom.includes(messages: :user).find(params[:id])
    # render template: 'views/chatrooms/show'
    @match = Match.find(params[:match_id])
    authorize @match_chat_room_messages
  end

  def create
    @match = Match.find(params[:match_id])
    if @match.chatroom.nil?
      @match_chat_room = ChatRoom.create(name: "match")
      authorize @match_chat_room
      @match.chatroom = @match_chat_room.id
      @match.save!
      # authorize @match
      redirect_to match_chat_room_path(match_id: params[:match_id], id: @match_chat_room)
    else
      skip_authorization
      redirect_to match_chat_room_path(match_id: params[:match_id], id: @match.chatroom)
    end
  end

end

app/views/chat_rooms/show.html.erb
<div class="chatboxcontainer">

    <div>
      <%= render 'shared/vertical-navbar', matches_count: @matches_count %>
    </div>
<!-- <div class="super-container"> -->
  <div class="items-chat">

    <div class="row-item">
      <%= cl_image_tag @match.item.pictures.first.key, class: "matched-cards" %>
      <%= cl_image_tag @match.other_item.pictures.first.key, class: "matched-cards" %>
    </div>

    <div class="form-container" id="matches-chat">
      <div id="chat-header">
          <h5>
            <%= @match.user1.username.capitalize %>
            |
            <%= @match.user2.username.capitalize %>
          </h5>
          <p>
            <% @match_chat_room_messages.name %>
          </p>
      </div>
          <div class="messages">
            <% @match_chat_room_messages.messages.each do |message| %>
              <%= render "messages/message", message: message, user_is_messages_author: message.user == current_user %>
            <% end %>
          </div>
          <div id="create-message">
            <%= simple_form_for [ @match_chat_room_messages, Message.new ], url: chat_room_messages_path(chat_room_id: params[:id]),remote: true, html: {autocomplete: "off" } do |f| %>
              <%= f.input :content, label: false, placeholder:"press enter to send the message" %>
            <% end %>
          </div>
              <button id="sweet-alert-demo" class="btn btn-primary">Deal done?</button>
              <%= link_to '', match_path(match_id: params[:match_id]), id: "ddlink", class: "hidden", method: :patch %>
    </div>
  </div>
<!-- </div> -->
</div>

<% content_for :after_js do %>
<script>
const scrollLastMessageIntoView = () => {

    const messages = document.querySelectorAll('.message');
    const lastMessage = messages[messages.length - 1];

    if (lastMessage !== undefined) {
        lastMessage.scrollIntoView();
    }
}
scrollLastMessageIntoView();
App['chat_room_<%= params[:id] %>'] = App.cable.subscriptions.create({ channel: 'ChatRoomsChannel', chat_room_id: <%= params[:id] %> }, {
    received: (data) => {
        if (data.current_user_id !== <%= current_user.id %>) {
            const messagesContainer = document.querySelector('.messages');
            messagesContainer.insertAdjacentHTML('beforeend', data.message_partial);
            scrollLastMessageIntoView();
        }
    }
})

const initSweetalert = (selector, options = {}) => {
  const swalButton = document.querySelector(selector);
  if (swalButton) { // protect other pages
    swalButton.addEventListener('click', () => {
      swal(options);
    });
  }
};

initSweetalert('#sweet-alert-demo', {
  title: "Did you exchange items?",
  text: "Press ok to close the deal.",
  icon: "success"
});

const button = document.querySelector("#sweet-alert-demo");
button.addEventListener('click', () => {
   document.querySelector(".swal-button.swal-button--confirm").addEventListener('click', () => {
      document.querySelector('#ddlink').click();
   });
});

</script>
<% end %>