config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  devise_for :users
  root to: 'pages#home'

  resources :items do
    get 'like'
    get 'dislike'
    member do
      get 'potential_matches'
    end
  end

  resources :matches, only: [:create, :index, :update] do
    # post 'exchanged'
    resources :chat_rooms, only: [ :show, :create ]
  end
  resources :chat_rooms, only: [] do
      resources :messages, only: [ :create ]
  end


end

app/views/shared/_button.html.erb
<!-- find scss code in button file (button). -->
<a href="link here" class="button">button</a>

app/views/shared/_delete-button.html.erb
_delete-button.html.erb

app/views/shared/_footer.html.erb
<div class="footer">
    <p>The sustainable exchange platform <i class="fas fa-sync-alt"></i></p>
    <!--   <div class="footer-links">
<!--   <div class="footer-links">
    <a href="https://github.com/alexandrezagame/fleapit"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/lewagonstockholm/"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div> -->
</div>

app/views/shared/_home-banner.html.erb
<!-- <div class="home-banner">
  <a class="button">Sign Up</a>
</div>
 -->

app/views/shared/_horizontal-navbar.html.erb
<!-- find scss in horizontal-navbar. HTML logo can be find in views/shared/logo
and scss for logo can be find in logo.scss.  -->
<div class="navbar navbar-expand-sm navbar-light nav-background">
    <%= link_to "#", class: "navbar-brand" do %>
    <h1 class="logo">Fleapit</h1>
    <% end %>
    <!--   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> -->
    <!-- This is the code for the hamburger menu icon.
The icon scss can be find in components/menu-burger.
We can add more links to add in our dropdown menu below.  -->
    <% if user_signed_in? %>
    <div class="nav-item dropdown">
        <%= image_tag "hamburger.svg", type: "button", class: "menu-hamburger", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Profile", items_path, class: "dropdown-item" %>
            <%= link_to "About Fleapit", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
    </div>
    <% else %>
    <%= link_to "Sign in", new_user_session_path, class:"button" %>
    <% end %>
</div>

app/views/shared/_landing-page-banner.html.erb
<!-- You can find the scss for the landing page under stylesheets/pages.  -->
<div class="home-banner">
  <h1 class="text-xl text-white semibold title-font mb-3">The non-monetary sustainable exchange platform</h1>
  <% if user_signed_in? %>
    <%= link_to 'Exchange', items_path, class:"button"  %>
    <% else %>
    <%= link_to 'Start exchanging', new_user_registration_path, class:"landing-page-button" %>
    <% end %>
</div>

app/views/shared/_landing-page-info.html.erb
<div class="landing-page-container">
    <div class="container-info-cards">
    <div class="fleapit-intro">
        <h3>What is Fleapit?</h3>
        <p>Fleapit is a virtual Second Hand shop,
            where you get items by exchanging for one of your own.
            This way you can get new items without having to spend any money,
            or impacting the environment.</p>
    </div>
    <div class="card-deck">
        <div class="card" style="width: 18rem;">
            <div class="far fa-check-circle" id="info-card"></div>
            <div class="card-body">
                <h5 class="card-title1">Sign Up</h5>
                <p class="card-text text-center">Join the sustainable exchange platform and take part in changing the way we consume, one item at the time.</p>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <div class="fab fa-angellist" id="info-card"></div>
            <div class="card-body">
                <h5 class="card-title1">Upload your items</h5>
                <p class="card-text text-center">Add a minimum of 1 item of your own that you are willing to exchange.</p>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <div class="far fa-laugh-beam" id="info-card"></div>
            <div class="card-body">
                <h5 class="card-title1">Exchange</h5>
                <p class="card-text text-center">Start exploring the endless opportunities at Fleapit. Prepare for the positive impact on the planet.</p>
            </div>
        </div>
    </div>
</div>
</div>
</div>

app/views/shared/_logo.html.erb
<%= link_to root_path, class: "navbar-brand" do %>
  <h3 class="logo">Fleapit</h3>
<% end %>

app/views/shared/_vertical-navbar.html.erb
<div class="vertical-navbar">
    <div class="row justify-content-between">
        <%= render 'shared/wheel' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="text-center">
        <%= cl_image_tag current_user.avatar.key, class: "avatar-xl-large" %>
        <div class="profile-infos">
            <h5>
                <%=  current_user.username.capitalize %>
            </h5>
            <!--       <img src="noun_ranking_1987379.png" alt=""> -->
            <h6>
                <%= current_user.location %>
            </h6>
        </div>
    </div>
    <div class="btn-group-vertical vertical-button">
      <div class="btn-group-vertical vertical-button button-container">
        <p class="matches_count"> <%= matches_count %></p>
        <%= link_to 'My Matches', matches_path, class:"button" %>
      </div>
        <% if current_user.items.size > 0 %>
        <%= link_to 'My Items', items_path, class:"button" %>
        <% else %>
        <%= link_to 'Upload', new_item_path, class:"button" %>
        <% end %>
        <%= link_to 'Home', root_path, class:"button" %>
    </div>
    <div class="navbar-logo">
        <%= render 'shared/logo' %>
    </div>
</div>

app/views/shared/_wheel.html.erb
    <div class="nav-item dropdown">
        <%= image_tag "hamburger.svg", type: "button", class: "menu-hamburger", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Upload", new_item_path, class: "dropdown-item" %>
            <%= link_to "Settings", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
    </div>