config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  devise_for :users
  root to: 'pages#home'

  resources :items do
    get 'like'
    get 'dislike'
    member do
      get 'potential_matches'
    end
  end

  resources :matches, only: [:create, :index, :update] do
    # post 'exchanged'
    resources :chat_rooms, only: [ :show, :create ]
  end
  resources :chat_rooms, only: [] do
      resources :messages, only: [ :create ]
  end


end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :item, class_name: "Item"
  belongs_to :other_item, class_name: "Item"
  belongs_to :user1, class_name: "User"
  belongs_to :user2, class_name: "User"
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = policy_scope(Match).order(created_at: :desc)
    # @matches = policy_scope
    # @matches = Match.where(user1_id: user.id).or(Match.where(user2_id: user.id))
    # matches variable = finding match where i am user 1 or user 2, merging two results.
    #display matches where one of the users is me

    # matches_td = []
    # matches.each do |match|
      # matches_td.push(match) if ( (match.user1_id == 52 && match.exchanged == false) || (match.user2_id == 52 && match.exchanged == false) )
    # end
    # @matches = matches
  end


  def update
    @match = Match.find(params[:match_id])
    authorize @match
    @match.exchanged = true
    @match.save!
    if @match.item.user.id == current_user.id
      @matches = Match.where(item_id: @match.item.id).or(Match.where(other_item_id: @match.item.id)).destroy_all
    else
      @matches = Match.where(item_id: @match.other_item.id).or(Match.where(other_item_id: @match.other_item.id)).destroy_all
    end
      redirect_to matches_path
  end
end

app/views/matches/_matchmodal.html.erb
<!-- Modal -->
<div class="modal fade" id="matchModal-<%= match.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        You got a Match!
      </div>
      <div class="modal-footer">
        <%= link_to "Keep Swiping", potential_matches_item_path(item), class:"button" %>
        <%= link_to "Go to Match",  matches_path, class:"button" %>
      </div>
    </div>
  </div>
</div>

app/views/matches/index.html.erb
<div class="big-container">
    <div>
        <%= render 'shared/vertical-navbar', matches_count: @matches_count %>
    </div>

    <% if @matches.size == 0 %>
          <div class="zero-items-paragraph2">
        <p>Hey <%= current_user.username  %>, it seems you don't have any matches yet.
          <br>
        </div>
    <% else %>

    <div class="matches-container">
        <div class="matches-banner"></div>
        <%  @matches.each do |match| %>
        <%  if match.user1_id == current_user.id %>
        <!-- daniel item-->
        <div class="matches-pairs">
            <div class="match-card mb-3" style="max-width: 400px;">
                <div data-item-id="<%= match.item_id %>">
                    <div class="row">
                        <div class="col-md-12">
                            <%= cl_image_tag match.item.pictures.first.key, class: "card-img" %>
                        </div>
                        <!-- user1 div cards, section left, my item info, on right, match info of other user -->
                        <!-- my item section -->
                        <!-- <div class="col-md-6 col-lg-6"> -->
                        <!-- <div class="card-body"> -->
                        <!-- <h6> -->
                        <%# match.user1.username %>
                        <!-- </h6>

                              <h6> -->
                        <%# match.user1.location %>
                        <!-- </h6> -->
                        <!-- <h3 class="card-text"> -->
                        <%# match.item.name %>
                        <!-- </h3> -->
                        <!-- <p class="card-text"> -->
                        <%# match.item.description %>
                        <!-- </p> -->
                        <!-- insert total price from the range -->
                        <!--    </div>
                      </div> -->
                    </div>
                </div>
            </div>
            <%= link_to '<i class="fas fa-exchange-alt"></i>'.html_safe, match_chat_rooms_path(match), method: :post, class: "button exchange-button"  %>
            <!-- other item section -->
            <!-- daniel wanted item-->
            <div class="match-card mb-3" style="max-width: 600px;">
                <div data-item-id="<%= match.item_id %>">
                    <div class="row">
                        <div class="col-md-6 col-lg-6">
                            <%= cl_image_tag match.other_item.pictures.first.key, class: "card-img" %>
                        </div>
                        <div class="col-md-6 col-lg-6">
                            <div class="card-body match-info">
                                <div class="match-user-info">
                                    <div>
                                        <h6>
                                            <%= match.user2.username.capitalize %>
                                        </h6>
                                        <h6>
                                            <%= match.user2.location %>
                                        </h6>
                                    </div>
                                    <div>
                                        <%= cl_image_tag match.user2.avatar.key, class: "avatar" %>
                                    </div>
                                </div>
                                <h5 class="card-title">
                                    <%= match.other_item.name %>
                                </h5>
                                <div class="scrollbar square scrollbar-lady-lips thin">
                                    <div class="force-overflow">
                                        <p class="card-text">
                                            <%= match.other_item.description %>
                                        </p>
                                    </div>
                                </div>
                                <!-- insert total price from the range -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <% else %>
        <!-- current_user item-->
        <div class="matches-pairs">
            <div class="match-card mb-3" style="max-width: 400px;">
                <div data-item-id="<%= match.other_item_id %>">
                    <div class="row">
                        <div class="col-md-12">
                            <%= cl_image_tag match.other_item.pictures.first.key, class: "card-img" %>
                        </div>
                        <!-- <div class="col-md-8">
                      <div class="card-body">
                          <h6>
                              <%# match.user2.username %>
                          </h6>
                          <h6>
                              <%# match.user2.location %>
                          </h6>
                          <h3 class="card-title">
                              <%# match.other_item.name %>
                          </h3>
                          <p class="card-text">
                              <%# match.other_item.description %>
                          </p>
                          insert total price from the range
                      </div>
                </div> -->
                    </div>
                </div>
            </div>
            <%= link_to '<i class="fas fa-exchange-alt"></i>'.html_safe, match_chat_rooms_path(match), method: :post, class: "button exchange-button"  %>
            <!-- current_user wanted item-->
            <div class="match-card mb-3" style="max-width: 600px;">
                <div data-item-id="<%= match.item_id %>">
                    <div class="row">
                        <div class="col-md-6 col-lg-6">
                            <%= cl_image_tag match.item.pictures.first.key, class: "card-img" %>
                        </div>
                        <div class="col-md-6 col-lg-6">
                            <div class="card-body match-info">
                                <div class="match-user-info">
                                    <div>
                                        <h6>
                                            <%= match.user1.username.capitalize %>
                                        </h6>
                                        <h6>
                                            <%= match.user1.location %>
                                        </h6>
                                    </div>
                                    <div>
                                        <%= cl_image_tag match.user1.avatar.key, class: "avatar" %>
                                    </div>
                                </div>
                                <h5 class="card-title">
                                    <%= match.item.name %>
                                </h5>
                                <div class="scrollbar square scrollbar-lady-lips thin">
                                    <div class="force-overflow">
                                        <p class="card-text">
                                            <%= match.item.description %>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- insert total price from the range -->
                    </div>
                </div>
            </div>
        </div>
        <% end %>
        <%# link_to 'show page button', item_path(item) %>
        <% end %>
    </div>
    <% end %>
</div>