config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  devise_for :users
  root to: 'pages#home'

  resources :items do
    get 'like'
    get 'dislike'
    member do
      get 'potential_matches'
    end
  end

  resources :matches, only: [:create, :index, :update] do
    # post 'exchanged'
    resources :chat_rooms, only: [ :show, :create ]
  end
  resources :chat_rooms, only: [] do
      resources :messages, only: [ :create ]
  end


end

app/models/item.rb
class Item < ApplicationRecord
  acts_as_votable
  acts_as_voter
  belongs_to :user
  has_many_attached :pictures
  has_many :matches, dependent: :destroy
  belongs_to :category

  validates :name, presence: true
  validates :brand, presence: true
  validates :description, presence: true
  validates :min_price, presence: true
  validates :max_price, presence: true
  # validates :description, presence: true
  # validates :gender, presence: true, inclusion {in: CATEGORIES/GENDER}
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # skip_before_action :authenticate_user!, only: []
  # before_action :set_item, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, except: :home
  def index
    @items = policy_scope(Item).order(created_at: :desc)
  end

  def potential_matches #showing potential matches from member routes
    # @items = Item.where.not(user: current_user)
    @my_item = Item.find(params[:id])
    @item = Item.where.not(user: current_user).where.not(id: @my_item.find_voted_items).order('RANDOM()').first
    if @item.nil?
      skip_authorization
    else
      authorize @item
    end
  end

  def like
    @wanted_item = Item.find(params[:item_id])
    @my_item = Item.find(params[:my_item])
    @wanted_item.liked_by @my_item
    # @wanted_item.vote_registered? #nest in if statement, check documentation
    # Step 1: Save wanted item
    # @wanted_item.save
    # Step 2: Check if my item was liked
    if @wanted_item.liked? @my_item
      @match = Match.new()
    # Step 3: If so, create new match
    # Step 4: Store my_item.id and wanted_item.id as item_id and other_item_id
      @match.item = @my_item
      @match.user1 = @my_item.user
      @match.user2 = @wanted_item.user
      #defining matches
      @match.other_item = @wanted_item
      @match.matched_date = Time.now
    # Step 5: Save match
      @match.save!
        #popup notification ITS A MATCH (clickable -> to matches view index)
        #trigger modal if @match.exist
    end
      respond_to do |format|
        format.html { redirect_to potential_matches_item_path(@my_item), alert: "LIKE" }
        format.js
      end
  end

  def dislike
    @not_wanted_item = Item.find(params[:item_id])
    @my_item = Item.find(params[:my_item])
    @not_wanted_item.disliked_by @my_item
    # @not_wanted_item.vote_registered? #check if u need line
    # @not_wanted_item.save
    respond_to do |format|
      format.html { redirect_to potential_matches_item_path(@my_item), alert: "DISLIKE" }
      format.js
    end
  end

  def create
    category = Category.find_by(name: params[:item][:category])
    @item = Item.new(name: params[:item][:name], description: params[:item][:description], brand: params[:item][:brand], min_price: params[:item][:min_price], max_price: params[:item][:max_price], category: category)
      params[:item][:pictures].each do |picture|
        @item.pictures.attach(picture)
      end
    # @item = Item.new(item_params)
    @item.user = current_user
    authorize @item #pundit
    if @item.save!
      redirect_to items_path, notice: "Item added"
    else
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    @item.assign_attributes(name: params[:item][:name]) if params[:item][:name]
    @item.assign_attributes(description: params[:item][:description]) if params[:item][:description]
    @item.assign_attributes(brand: params[:item][:brand]) if params[:item][:brand]
    @item.assign_attributes(min_price: params[:item][:min_price]) if params[:item][:min_price]
    @item.assign_attributes(max_price: params[:item][:max_price]) if params[:item][:max_price]
      if params[:item][:category]
        category = Category.find_by(name: params[:item][:category])
        @item.assign_attributes(category: category)
      end
      if params[:item][:pictures]
        params[:item][:pictures].each do |picture|
          @item.pictures.attach(picture)
        end
      end
    authorize @item #pundit
    if @item.save
      redirect_to items_path, notice: "Item updated"
    else
      render :edit
    end
  end

  def edit
    @item = Item.find(params[:id])
    authorize @item #pundit
  end

  def new
    @item = Item.new
    authorize @item
  end

  def destroy
    @item = Item.find(params[:id])
    Match.where(item_id: @item.id).or(Match.where(other_item_id: @item.id)).destroy_all
    authorize @item #pundit
    @item.destroy
    redirect_to items_path, notice: "Item destroyed"
  end

  private
  # def set_item
  #   @item = Item.find(params[:id])
  # end

  def item_params
    params.require(:item).permit(:name, :description, :category, :brand, :min_price, :max_price, pictures: [])
  end
end

app/views/items/_form.html.erb
<%= simple_form_for item do |f| %>
    <%= f.input :name %>
    <%= f.input :brand %>
    <%= f.input :description, as: :text, :input_html => { :cols => 5, :rows => 5 }%>
    <%= f.input :category, :collection => ["Home & decorations", "Women clothes", "Men clothes", "Accessories", "Electronics", "Outdoors", "Hobby", "Tools"]%>
    <%= f.input :min_price, as: :hidden, input_html: { value: "min" }, id: "minPriceInput" %>
    <%= f.input :max_price, as: :hidden, input_html: { value: "max" }, id: "maxPriceInput" %>
    <p class="select required">Price range <abbr title="required">*</abbr></p>
    <div id="slider"></div>
    <div id="price-container">
      <div class="price-display">
    <div id="lowerPrice"></div>
    <h6> - </h6>
    <div id="upperPrice"></div><h6> kr</h6>
  </div>
    </div>

    <%= f.input :pictures, as: :file, input_html: { class: 'd-none', multiple: true }, label_html: { class: 'upload-photo'}, label: '📷 Upload photos' %>
    <div class="form-button">
    <%= link_to 'Back', items_path, class: "button" %>
    <%= f.button :submit, class: "button" %>
    </div>
  <% end %>

app/views/items/create.html.erb
<div class="big-container">
    <%= render 'shared/vertical-navbar', matches_count: @matches_count %>
    <h1>Items#create</h1>
    <p>Find me in app/views/items/create.html.erb</p>
</div>

app/views/items/destroy.html.erb
<div class="big-container">
    <%= render 'shared/vertical-navbar', matches_count: @matches_count %>
    <h1>Items#destroy</h1>
    <p>Find me in app/views/items/destroy.html.erb</p>
</div>

app/views/items/dislike.js.erb
// find the card that was clicked on

window.location.replace("<%= potential_matches_item_path(@my_item) %>");
// document.querySelector("[data-item-id='<%= @not_wanted_item.id %>']").remove();

// remove the html of the card

app/views/items/edit.html.erb
<div class="big-container">
    <%= render 'shared/vertical-navbar', matches_count: @matches_count %>
    <div class="form-container">
        <h5>Edit item</h5>
        <div class="new_item">
            <%= link_to '', item_path(@item), method: :delete, data: {confirm: "Are you sure you want to delete this item?"}, class: "fa fa-trash delete-button"  %>
            <div class="form-card">
                <div class="form-information">
                    <%= render 'form', item: @item %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/items/index.html.erb
<div class="big-container">
    <div>
        <%= render 'shared/vertical-navbar', matches_count: @matches_count %>
    </div>
    <% if current_user.items.size == 0 %>
    <div class="items-button">
          <div class="zero-items-paragraph">
        <p>Hey <%= current_user.username  %>, welcome to Fleapit, it seems you don't have any items yet.
          <br>
        Press on the button below to add your first item
        and start exchanging with other users!</p>
        </div>
    <div class="items-button-zero">
        <%= link_to 'Upload your first item', new_item_path, class: "button" %>
    </div>
    <% else %>

    <div class="items-container">
        <div class="row justify-content-center">
            <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10">
                <% @items.each_with_index do |item, index| %>
                <div class="card-trip d-flex">
                    <div class="carousel-card-information">
                        <%= link_to '', edit_item_path(item), class:"fas fa-edit", id:"edit-button" %>
                        <h2>
                            <%= item.name %>
                        </h2>
                        <br>
                        <h5>
                            <%= item.description %>
                        </h5>
                        <br>
                        <p>
                            <%= item.min_price %> kr -
                            <%= item.max_price %> kr
                        </p>
                        <p>

                            <%= link_to 'Exchange this item', potential_matches_item_path(item), class:"button exchangebutton", style:"padding: 10px;"%>

                        </p>
                    </div>
                    <div id="carousel<%=index%>" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <% item.pictures.each_with_index do |picture, index| %>
                            <li data-target="carousel<%=index%>" data-slide-to="<%=index%>" class="<%= 'active' if index == 0 %>"></li>
                            <% end %>
                        </ol>
                        <div class="carousel-inner">
                            <% item.pictures.each_with_index do |picture, index| %>
                            <div class="carousel-item <%= 'active' if index == 0 %>">
                                <%= cl_image_tag picture.key, class: "items-image d-block" %>
                            </div>
                            <% end %>
                        </div>
                        <a class="carousel-control-prev" href="#carousel<%=index%>" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carousel<%=index%>" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                    <%# link_to 'Swipe this item', potential_matches_item_path(item)  %>
                </div>
                <% end %>
            </div>
            <%# link_to 'Upload an item', new_item_path  %>
        </div>
    </div>
    <% end %>
</div>

app/views/items/item_params.html.erb
<h1>Items#item_params</h1>
<p>Find me in app/views/items/item_params.html.erb</p>

app/views/items/like.js.erb
const displayModal = (modal, matchid) => {
  console.log(matchid);
  const potentialmatch = document.querySelector("#potentialMatches");
  potentialmatch.insertAdjacentHTML('beforeend', modal);
  $(`#matchModal-${matchid}`).modal();
};

<% if @match %>
  displayModal('<%= j render "matches/matchmodal", match: @match, item: @my_item %>', '<%= @match.id %>');
  <% else %>
  window.location.replace("<%= potential_matches_item_path(@my_item) %>");
<% end %>


// document.querySelector("[data-item-id='<%= @wanted_item.id %>']").remove();

app/views/items/new.html.erb
<div class="big-container">
    <%= render 'shared/vertical-navbar', matches_count: @matches_count %>
        <div class="form-container">
            <h5>Upload Item</h5>
            <div class="form-card">
                <div class="form-information">
                    <%= render 'form', item: @item %>
                </div>
            </div>
        </div>
    </div>

app/views/items/potential_matches.html.erb
<div class="big-container">
    <div>
        <%= render 'shared/vertical-navbar', matches_count: @matches_count %>
    </div>
    <% if @item %>
    <div class="items-container">
        <div class="row justify-content-center" id="potentialMatches">
            <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10">

                <div data-item-id="<%= @item.id %>">
                    <div class="matches-card-trip">
                        <div class="match-image-items">
                            <% @item.pictures.each do |picture| %>
                            <%= cl_image_tag picture.key, class: "items-image" %>
                            <% end %>
                        </div>
                        <div class="matches-card-information-bis">
                            <div class="matches-top-card">
                                <div>
                                    <h5>
                                        <%= @item.name %>
                                    </h5>
                                    <h6>
                                        <%= @item.user.location %>
                                    </h6>
                                </div>
                                <div class="matches-card-information-user">
                                    <%= cl_image_tag @item.user.avatar.key, class: "avatar" %>
                                    <h6>
                                        <%= @item.user.username.capitalize %>
                                    </h6>
                                </div>
                            </div>
                            <div class="scrollbar square scrollbar-lady-lips thin" id="matches-scrollbar">
                                <div class="force-overflow">
                                    <p class="card-text">
                                        <%= @item.description %>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="voting">
                            <%= link_to '', item_dislike_path(@item, my_item: @my_item), class:"fas fa-heart-broken dislike-button", remote: true  %>
                            <p>
                              <%= @item.min_price %> - <%= @item.max_price %> kr
                            </p>
                            <%= link_to '', item_like_path(@item, my_item: @my_item), class:"fas fa-heart like-button", remote: true %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <% else %>
    <div class="zero-items-paragraph2">
        <h1>No more items for this category..</h1>
        <%= link_to 'Choose other item', items_path, class:"button" %>
    </div>
    <% end %>
</div>

app/views/items/set_item.html.erb
<div class="big-container">
    <%= render 'shared/vertical-navbar', matches_count: @matches_count %>
    <h1>Items#set_item</h1>
    <p>Find me in app/views/items/set_item.html.erb</p>
</div>

app/views/items/show.html.erb
<div class="big-container">
    <%= render 'shared/vertical-navbar', matches_count: @matches_count %>
    <h1>Items#show</h1>
    <p>Find me in app/views/items/show.html.erb</p>
</div>

app/views/items/update.html.erb
<div class="big-container">
    <%= render 'shared/vertical-navbar', matches_count: @matches_count %>
    <h1>Items#update</h1>
    <p>Find me in app/views/items/update.html.erb</p>
</div>